### ISSUE TITLE
Implement initial habitat-container

### ISSUE THREAD

**Issue by entelecheia** [entelecheia/habitat-container#1]
## Summary

Implement a Docker container to run Habitat-Lab environments.

## Tasks

- [ ] Create Dockerfile
  - Use Python base image
  - Install Habitat-Lab and dependencies
- [ ] Copy Habitat-Lab source code
- [ ] Create entrypoint script
  - Import Habitat-Lab and start Python shell
- [ ] Include base Habitat-Lab example configs
- [ ] Create configs volume
  - For mounting custom config files
- [ ] Write README
  - Usage
  - Configs
  - Examples
  
## Requirements

- Dockerfile builds image with Habitat-Lab installed
- Entrypoint launches Python shell with Habitat imported
- Base config files included
- Configs volume for custom configs
- README explains usage and configuration

## Resources

- Habitat-Lab repo: https://github.com/facebookresearch/habitat-lab
